In [79]:
import numpy as np
import pandas as pd

In [102]:
df1 = pd.read_csv("D:/ml/deepwalk-master/kospi200/data/kospi200.csv",
                 index_col = 0,
                 header=0,
                 encoding='cp949', sep=',')

In [103]:
df1.head()

시가      고가      저가     현재가      거래량
일자                                                 
2020-01-31  290.24  291.47  284.53  284.53  101,455
2020-01-30  293.27  294.11  287.09  288.37  101,535
2020-01-29  294.38  295.67  292.45  293.98   85,731
2020-01-28  294.98  296.30  291.30  292.77  130,172
2020-01-23  303.77  304.72  301.71  302.33   86,908

In [104]:
print(df1.shape)

(426, 5)


In [105]:
df2 = pd.read_csv("D:/ml/deepwalk-master/kospi200/data/samsung.csv",
                 index_col = 0,
                 header=0,
                 encoding='cp949', sep=',')

In [106]:
df2.head()

시가      고가      저가      종가         거래량
일자                                                    
2020-01-31  57,800  58,400  56,400  56,400  19,749,457
2020-01-30  58,800  58,800  56,800  57,200  20,821,939
2020-01-29  59,100  59,700  58,800  59,100  16,446,102
2020-01-28  59,400  59,400  58,300  58,800  23,664,541
2020-01-23  61,800  61,800  60,700  60,800  14,916,555

In [107]:
print(df2.shape)

(426, 5)


In [108]:
df1.dtypes

시가     float64
고가     float64
저가     float64
현재가    float64
거래량     object
dtype: object

In [109]:
df2.dtypes

시가     object
고가     object
저가     object
종가     object
거래량    object
dtype: object

In [110]:
for i in range(len(df1.index)):
    
    df1.iloc[i,4] = int(df1.iloc[i,4].replace(',',''))

In [111]:
df1.head(3)

시가      고가      저가     현재가     거래량
일자                                                
2020-01-31  290.24  291.47  284.53  284.53  101455
2020-01-30  293.27  294.11  287.09  288.37  101535
2020-01-29  294.38  295.67  292.45  293.98   85731

In [112]:
for i in range(len(df2.index)):
    
    for j in range(len(df2.iloc[i])):
        
        df2.iloc[i,j] = int(df2.iloc[i,j].replace(',',''))

In [113]:
df2.head()

시가     고가     저가     종가       거래량
일자                                              
2020-01-31  57800  58400  56400  56400  19749457
2020-01-30  58800  58800  56800  57200  20821939
2020-01-29  59100  59700  58800  59100  16446102
2020-01-28  59400  59400  58300  58800  23664541
2020-01-23  61800  61800  60700  60800  14916555

In [114]:
df1 = df1.sort_values(['일자'], ascending=True)
df2 = df2.sort_values(['일자'], ascending=True)

In [115]:
df1.head(2)

시가      고가      저가     현재가     거래량
일자                                                
2018-05-04  320.56  321.00  316.75  316.75  173911
2018-05-08  317.79  319.53  314.95  315.87  141252

In [116]:
df2.head(2)

시가     고가     저가     종가       거래량
일자                                              
2018-05-04  53000  53900  51800  51900  39565391
2018-05-08  52600  53200  51900  52600  23104720

In [117]:
df1.dtypes

시가     float64
고가     float64
저가     float64
현재가    float64
거래량     object
dtype: object

In [118]:
df1['거래량'] = df1['거래량'].astype('float64')

In [119]:
df2.dtypes

시가     object
고가     object
저가     object
종가     object
거래량    object
dtype: object

In [120]:
df2['시가'] = df2['시가'].astype('float64')
df2['고가'] = df2['고가'].astype('float64')
df2['저가'] = df2['저가'].astype('float64')
df2['종가'] = df2['종가'].astype('float64')
df2['거래량'] = df2['거래량'].astype('float64')

In [121]:
df1.dtypes

시가     float64
고가     float64
저가     float64
현재가    float64
거래량    float64
dtype: object

In [122]:
df2.dtypes

시가     float64
고가     float64
저가     float64
종가     float64
거래량    float64
dtype: object

In [123]:
df1 = df1.values
df2 = df2.values

In [124]:
type(df1)

numpy.ndarray

In [125]:
type(df2)

numpy.ndarray

In [126]:
df1

array([[   320.56,    321.  ,    316.75,    316.75, 173911.  ],
       [   317.79,    319.53,    314.95,    315.87, 141252.  ],
       [   315.93,    316.08,    312.6 ,    314.42, 123610.  ],
       ...,
       [   294.38,    295.67,    292.45,    293.98,  85731.  ],
       [   293.27,    294.11,    287.09,    288.37, 101535.  ],
       [   290.24,    291.47,    284.53,    284.53, 101455.  ]])

In [127]:
df2

array([[   53000.,    53900.,    51800.,    51900., 39565391.],
       [   52600.,    53200.,    51900.,    52600., 23104720.],
       [   52600.,    52800.,    50900.,    50900., 16128305.],
       ...,
       [   59100.,    59700.,    58800.,    59100., 16446102.],
       [   58800.,    58800.,    56800.,    57200., 20821939.],
       [   57800.,    58400.,    56400.,    56400., 19749457.]])

In [128]:
df1.shape

(426, 5)

In [129]:
df2.shape

(426, 5)

In [130]:
np.save('kospi200.npy', arr=df1)
np.save('samsung.npy', arr=df2)

## npy 데이터 불러오기

In [35]:
#kospi200 = np.load('kospi200.npy')
#samsung = np.load('samsung.npy')

In [131]:
kospi200 = df1.copy()
samsung = df2.copy()

In [132]:
print(kospi200)
print(samsung)
print(kospi200.shape)
print(samsung.shape)

[[   320.56    321.      316.75    316.75 173911.  ]
 [   317.79    319.53    314.95    315.87 141252.  ]
 [   315.93    316.08    312.6     314.42 123610.  ]
 ...
 [   294.38    295.67    292.45    293.98  85731.  ]
 [   293.27    294.11    287.09    288.37 101535.  ]
 [   290.24    291.47    284.53    284.53 101455.  ]]
[[   53000.    53900.    51800.    51900. 39565391.]
 [   52600.    53200.    51900.    52600. 23104720.]
 [   52600.    52800.    50900.    50900. 16128305.]
 ...
 [   59100.    59700.    58800.    59100. 16446102.]
 [   58800.    58800.    56800.    57200. 20821939.]
 [   57800.    58400.    56400.    56400. 19749457.]]
(426, 5)
(426, 5)


In [133]:
def split_xy5(dataset, time_steps, y_column):
    
    x, y = list(), list()
    
    for i in range(len(dataset)):
        
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column
        
        
        if y_end_number > len(dataset):
            break
            
        
        tmp_x = dataset[i:x_end_number, :]
        tmp_y = dataset[x_end_number:y_end_number, 3]
        
        x.append(tmp_x)
        y.append(tmp_y)
        
    return np.array(x), np.array(y)


x,y = split_xy5(samsung, 5, 1)

print(x[0,:], "\n", y[0])
print(x.shape)
print(y.shape)
        
        

[[   53000.    53900.    51800.    51900. 39565391.]
 [   52600.    53200.    51900.    52600. 23104720.]
 [   52600.    52800.    50900.    50900. 16128305.]
 [   51700.    51700.    50600.    51600. 13905263.]
 [   52000.    52200.    51200.    51300. 10314997.]] 
 [50100.]
(421, 5, 5)
(421, 1)


In [134]:
from sklearn.model_selection import train_test_split

In [135]:
x_train, x_test, y_train, y_test = train_test_split(x,
                                                   y,
                                                   random_state=1,
                                                   test_size = 0.3)

In [136]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(294, 5, 5)
(127, 5, 5)
(294, 1)
(127, 1)


In [137]:
x_train = np.reshape(x_train,
                    (x_train.shape[0], x_train.shape[1]*x_train.shape[2]))

In [138]:
x_test = np.reshape(x_test,
                   (x_test.shape[0], x_test.shape[1]*x_test.shape[2]))

In [139]:
print(x_train.shape)
print(x_test.shape)

(294, 25)
(127, 25)


In [140]:
from sklearn.preprocessing import StandardScaler

In [141]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)
print(x_train_scaled[0, :])

[ 1.13392563  1.07633086  1.02393741  0.93187013 -0.028819    1.05994459
  1.04756614  1.06686328  0.94933344  1.53138774  0.79093879  0.80213886
  0.84540479  0.81507608  0.10811605  0.73712199  0.68893234  0.71073997
  0.69657856  0.37360361  0.85647275  0.80021877  0.80910994  0.69442952
 -0.16973555]


In [142]:
from keras.models import Sequential
from keras.layers import Dense

In [143]:
model = Sequential()

In [144]:
model.add(Dense(64, input_shape=(25,)))

In [145]:
model.add(Dense(32, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))

In [146]:
model.add(Dense(1))

In [147]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_20 (Dense)             (None, 64)                1664      
_________________________________________________________________
dense_21 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_22 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_23 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_24 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_25 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_26 (Dense)             (None, 1)                

In [148]:
model.compile(optimizer='adam', loss='mse', metrics = ['mse'])

In [154]:
#from keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import EarlyStopping

In [155]:
early_stopping = EarlyStopping(patience=20)

In [156]:
model.compile(optimizer='adam', loss='mse', metrics = ['mse'])

In [157]:
model.fit(x_train_scaled, y_train, validation_split=0.2, verbose = 1,
          batch_size = 1, epochs = 100, callbacks = [early_stopping])

Epoch 1/100
235/235 [==============================] - 0s 2ms/step - loss: 1648222720.0000 - mse: 1648222720.0000 - val_loss: 694129792.0000 - val_mse: 694129792.0000
Epoch 2/100
235/235 [==============================] - 0s 976us/step - loss: 905580224.0000 - mse: 905580224.0000 - val_loss: 765533632.0000 - val_mse: 765533632.0000
Epoch 3/100
235/235 [==============================] - 0s 1ms/step - loss: 801375104.0000 - mse: 801375104.0000 - val_loss: 568044416.0000 - val_mse: 568044416.0000
Epoch 4/100
235/235 [==============================] - 0s 1ms/step - loss: 593374464.0000 - mse: 593374464.0000 - val_loss: 378529216.0000 - val_mse: 378529216.0000
Epoch 5/100
235/235 [==============================] - 0s 983us/step - loss: 319429440.0000 - mse: 319429440.0000 - val_loss: 286339616.0000 - val_mse: 286339616.0000
Epoch 6/100
235/235 [==============================] - 0s 1ms/step - loss: 181023120.0000 - mse: 181023120.0000 - val_loss: 141185072.0000 - val_mse: 141185072.0000
Epoc

In [158]:
loss, mse = model.evaluate(x_test_scaled, y_test, batch_size=1)
print('loss : ', loss)
print('mse : ', mse)


127/127 [==============================] - 0s 887us/step - loss: 1272636.8750 - mse: 1272636.8750
loss :  1272636.875
mse :  1272636.875


In [159]:
y_pred = model.predict(x_test_scaled)

for i in range(5):
    print('종가 : ', y_test[i], '/ 예측가 : ', y_pred[i])

종가 :  [52200.] / 예측가 :  [51824.1]
종가 :  [41450.] / 예측가 :  [42691.363]
종가 :  [49650.] / 예측가 :  [50714.387]
종가 :  [44800.] / 예측가 :  [46184.29]
종가 :  [49500.] / 예측가 :  [48662.184]
