In [32]:
import numpy as np
x1 = np.array([range(1, 101), range(101, 201)])
x2 = np.array([range(501, 601), range(601, 701)])
y = np.array([range(1, 101), range(101, 201)])

In [33]:
x1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
        166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 17

In [34]:
x2

array([[501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
        514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
        527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
        540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
        553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
        566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
        579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
        592, 593, 594, 595, 596, 597, 598, 599, 600],
       [601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613,
        614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626,
        627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639,
        640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652,
        653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665,
        666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 67

In [35]:
y

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
        166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 17

In [36]:
print(x1.shape)
print(x2.shape)
print(y.shape)

(2, 100)
(2, 100)
(2, 100)


In [37]:
x1 = np.transpose(x1)
x2 = np.transpose(x2)
y = np.transpose(y)
print(x1.shape)
print(x2.shape)
print(y.shape)

(100, 2)
(100, 2)
(100, 2)


In [67]:
from sklearn.model_selection import train_test_split

In [68]:
x1_train, x1_test, y_train, y_test = train_test_split(x1,y,random_state=2020,
                                                      test_size=0.2,shuffle=False)
                                                      
                                                      

In [69]:
x1_val, x1_test, y_val, y_test = train_test_split(x1_test,y_test,
                                                 random_state = 2020,
                                                  test_size=0.5,
                                                 shuffle = False)

In [70]:
x2_train, x2_test = train_test_split(
x2, random_state=2020, test_size=0.2, shuffle = False
)

In [71]:
x2_val, x2_test = train_test_split(
x2_test, random_state=2020, test_size=0.5, shuffle = False
)


In [72]:
print('x2_train.shape : ', x2_train.shape)
print('x2_val.shape : ', x2_val.shape)
print('x2_test.shape : ', x2_test.shape)

x2_train.shape :  (80, 2)
x2_val.shape :  (10, 2)
x2_test.shape :  (10, 2)


In [75]:
from keras.models import Sequential, Model
from keras.layers import Dense, Input

In [76]:
input1 = Input(shape=(2,))
dense1 = Dense(100, activation='relu')(input1)
dense1 = Dense(30)(dense1)
dense1 = Dense(7)(dense1)

In [77]:
input2 = Input(shape=(2,))
dense2 = Dense(50, activation='relu')(input2)
dense2 = Dense(30)(dense2)
dense2 = Dense(7)(dense2)

In [78]:
from keras.layers.merge import concatenate
merge1 = concatenate([dense1, dense2])

In [79]:
output1 = Dense(30)(merge1)
output1 = Dense(7)(output1)
output1 = Dense(2)(output1)

In [80]:
model = Model(inputs = [input1, input2],
outputs = output1
)

In [81]:
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_5 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
input_6 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
dense_18 (Dense)                (None, 100)          300         input_5[0][0]                    
__________________________________________________________________________________________________
dense_21 (Dense)                (None, 50)           150         input_6[0][0]                    
____________________________________________________________________________________________

In [82]:
model.compile(loss='mse', optimizer='adam', metrics = ['mse'])

In [87]:
model.fit([x1_train, x2_train], y_train,
         epochs=50, batch_size=1, 
         validation_data=([x1_val, x2_val], y_val))

Epoch 1/50
80/80 [==============================] - 0s 3ms/step - loss: 1361.9452 - mse: 1361.9452 - val_loss: 410.1905 - val_mse: 410.1905
Epoch 2/50
80/80 [==============================] - 0s 1ms/step - loss: 142.7801 - mse: 142.7801 - val_loss: 254.4222 - val_mse: 254.4222
Epoch 3/50
80/80 [==============================] - 0s 1ms/step - loss: 23.4514 - mse: 23.4514 - val_loss: 8.4097 - val_mse: 8.4097
Epoch 4/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4451 - mse: 0.4451 - val_loss: 1.1092 - val_mse: 1.1092
Epoch 5/50
80/80 [==============================] - 0s 1ms/step - loss: 0.0252 - mse: 0.0252 - val_loss: 0.4762 - val_mse: 0.4762
Epoch 6/50
80/80 [==============================] - 0s 1ms/step - loss: 0.0131 - mse: 0.0131 - val_loss: 0.2730 - val_mse: 0.2730
Epoch 7/50
80/80 [==============================] - 0s 1ms/step - loss: 0.0133 - mse: 0.0133 - val_loss: 0.3670 - val_mse: 0.3670
Epoch 8/50
80/80 [==============================] - 0s 1ms/step - loss

In [88]:
mse = model.evaluate([x1_test, x2_test], y_test, batch_size=1)
print("mse : ", mse)

10/10 [==============================] - 0s 898us/step - loss: 0.3341 - mse: 0.3341
mse :  [0.33412978053092957, 0.33412978053092957]


In [89]:
y_predict = model.predict([x1_test, x2_test])
print("y1 예측값 : \n", y_predict)

y1 예측값 : 
 [[ 90.78453  190.74878 ]
 [ 91.71093  191.69345 ]
 [ 92.63732  192.63817 ]
 [ 93.56373  193.5829  ]
 [ 94.49013  194.52757 ]
 [ 95.41652  195.47229 ]
 [ 96.33665  196.41115 ]
 [ 97.244705 197.33884 ]
 [ 98.14651  198.25992 ]
 [ 99.04292  199.17532 ]]
