In [2]:
import numpy as np
x = np.array([range(1, 101), range(101, 201)])
y1 = np.array([range(501, 601), range(601, 701)])
y2 = np.array([range(1, 101), range(101, 201)])

In [3]:
print(x.shape)
print(y1.shape)
print(y2.shape)

(2, 100)
(2, 100)
(2, 100)


In [4]:
x = np.transpose(x)
y1 = np.transpose(y1)
y2 = np.transpose(y2)

In [5]:
print(x[:5])
print(y1[:5])
print(y2[:5])

[[  1 101]
 [  2 102]
 [  3 103]
 [  4 104]
 [  5 105]]
[[501 601]
 [502 602]
 [503 603]
 [504 604]
 [505 605]]
[[  1 101]
 [  2 102]
 [  3 103]
 [  4 104]
 [  5 105]]


In [6]:
print(x.shape)
print(y1.shape)
print(y2.shape)

(100, 2)
(100, 2)
(100, 2)


In [7]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y1_train, y1_test = train_test_split(x,
                                                     y1,
                                                     random_state=2020,
                                                     test_size = 0.2,
                                                     shuffle=False)

In [11]:
x_val, x_test, y1_val, y1_test = train_test_split(x_test,
                                                  y1_test,
                                                  random_state=2020,
                                                  test_size = 0.5,
                                                  shuffle = False)

In [13]:
y2_train, y2_test = train_test_split(y2,
                                    random_state=2020,
                                    test_size = 0.2,
                                    shuffle = False)

In [14]:
y2_val, y2_test = train_test_split(y2_test,
                                  random_state=2020,
                                  test_size = 0.5,
                                  shuffle = False)

In [15]:
print('y2_train.shape : ', y2_train.shape)
print('y2_val.shape : ', y2_val.shape)
print('y2_test.shape : ', y2_test.shape)


y2_train.shape :  (80, 2)
y2_val.shape :  (10, 2)
y2_test.shape :  (10, 2)


In [16]:
from keras.models import Sequential, Model
from keras.layers import Dense, Input

Using TensorFlow backend.


In [28]:
del output1, output2, model

In [29]:
input1 = Input(shape=(2,))
dense1 = Dense(100, activation='relu')(input1)
dense1 = Dense(30)(dense1)
dense1 = Dense(7)(dense1)

In [30]:
output1 = Dense(30)(dense1)
output1 = Dense(7)(output1)
output1 = Dense(2)(output1)

In [31]:
output2 = Dense(30)(dense1)
output2 = Dense(7)(output2)
output2 = Dense(2)(output2)

In [32]:
model = Model(inputs = input1, outputs=[output1, output2])

In [33]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
dense_12 (Dense)                (None, 100)          300         input_2[0][0]                    
__________________________________________________________________________________________________
dense_13 (Dense)                (None, 30)           3030        dense_12[0][0]                   
__________________________________________________________________________________________________
dense_14 (Dense)                (None, 7)            217         dense_13[0][0]                   
____________________________________________________________________________________________

In [37]:
model.compile(loss='mse', optimizer='adam', metrics=['mse'])

In [38]:
model.fit(x_train, [y1_train, y2_train],
          epochs=50, batch_size=1,
          validation_data=(x_val, [y1_val, y2_val]))

Epoch 1/50
80/80 [==============================] - 0s 3ms/step - loss: 103.0427 - dense_17_loss: 86.0348 - dense_20_loss: 17.0079 - dense_17_mse: 86.0348 - dense_20_mse: 17.0079 - val_loss: 37.0513 - val_dense_17_loss: 35.7854 - val_dense_20_loss: 1.2659 - val_dense_17_mse: 35.7854 - val_dense_20_mse: 1.2659
Epoch 2/50
80/80 [==============================] - 0s 1ms/step - loss: 0.1168 - dense_17_loss: 0.0675 - dense_20_loss: 0.0493 - dense_17_mse: 0.0675 - dense_20_mse: 0.0493 - val_loss: 52.1681 - val_dense_17_loss: 50.3268 - val_dense_20_loss: 1.8413 - val_dense_17_mse: 50.3268 - val_dense_20_mse: 1.8413
Epoch 3/50
80/80 [==============================] - 0s 1ms/step - loss: 0.0086 - dense_17_loss: 0.0063 - dense_20_loss: 0.0023 - dense_17_mse: 0.0063 - dense_20_mse: 0.0023 - val_loss: 48.4014 - val_dense_17_loss: 46.6483 - val_dense_20_loss: 1.7531 - val_dense_17_mse: 46.6483 - val_dense_20_mse: 1.7531
Epoch 4/50
80/80 [==============================] - 0s 1ms/step - loss: 0.0083 

Epoch 28/50
80/80 [==============================] - 0s 1ms/step - loss: 0.1430 - dense_17_loss: 0.0814 - dense_20_loss: 0.0616 - dense_17_mse: 0.0814 - dense_20_mse: 0.0616 - val_loss: 9.0753 - val_dense_17_loss: 8.2827 - val_dense_20_loss: 0.7926 - val_dense_17_mse: 8.2827 - val_dense_20_mse: 0.7926
Epoch 29/50
80/80 [==============================] - 0s 1ms/step - loss: 0.0407 - dense_17_loss: 0.0352 - dense_20_loss: 0.0054 - dense_17_mse: 0.0352 - dense_20_mse: 0.0054 - val_loss: 9.1714 - val_dense_17_loss: 8.7120 - val_dense_20_loss: 0.4594 - val_dense_17_mse: 8.7120 - val_dense_20_mse: 0.4594
Epoch 30/50
80/80 [==============================] - 0s 1ms/step - loss: 0.4709 - dense_17_loss: 0.0530 - dense_20_loss: 0.4179 - dense_17_mse: 0.0530 - dense_20_mse: 0.4179 - val_loss: 9.4896 - val_dense_17_loss: 9.1427 - val_dense_20_loss: 0.3469 - val_dense_17_mse: 9.1427 - val_dense_20_mse: 0.3469
Epoch 31/50
80/80 [==============================] - 0s 2ms/step - loss: 0.2772 - dense_17_

In [39]:
mse = model.evaluate(x_test, [y1_test, y2_test], batch_size=1)
print("mse : ", mse)
y1_predict, y2_predict = model.predict(x_test)
print("y1 예측값 : \n", y1_predict, "\n y2 예측값 : \n", y2_predict)

10/10 [==============================] - 0s 798us/step - loss: 163.9500 - dense_17_loss: 153.6185 - dense_20_loss: 10.3315 - dense_17_mse: 153.6185 - dense_20_mse: 10.3315
mse :  [163.9500274658203, 153.61849975585938, 10.331521987915039, 153.61849975585938, 10.331521987915039]
y1 예측값 : 
 [[597.916   699.0591 ]
 [599.84296 701.1443 ]
 [601.7699  703.2294 ]
 [603.697   705.3145 ]
 [605.6239  707.39966]
 [607.55096 709.48486]
 [609.4779  711.5699 ]
 [611.40497 713.65515]
 [613.3319  715.74023]
 [615.2589  717.8255 ]] 
 y2 예측값 : 
 [[ 87.9472   190.24957 ]
 [ 88.65564  191.20616 ]
 [ 89.364044 192.16273 ]
 [ 90.072525 193.11932 ]
 [ 90.78094  194.07593 ]
 [ 91.48943  195.03249 ]
 [ 92.197845 195.9891  ]
 [ 92.906334 196.94574 ]
 [ 93.61473  197.9023  ]
 [ 94.32319  198.85893 ]]
