In [10]:
import numpy as np
x1 = np.array([range(1, 101), range(101, 201)])
y1 = np.array([range(1, 101), range(101, 201)])
x2 = np.array([range(501, 601), range(601, 701)])
y2 = np.array([range(501, 601), range(601, 701)])
y3 = np.array([range(701, 801), range(801, 901)])

In [11]:
x1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
        166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 17

In [12]:
print(x1.shape)
print(x2.shape)
print(y1.shape)
print(y2.shape)
print(y3.shape)

(2, 100)
(2, 100)
(2, 100)
(2, 100)
(2, 100)


In [13]:
x1 = np.transpose(x1)
y1 = np.transpose(y1)
x2 = np.transpose(x2)
y2 = np.transpose(y2)
y3 = np.transpose(y3)
print(x1.shape)
print(x2.shape)
print(y1.shape)
print(y2.shape)
print(y3.shape)

(100, 2)
(100, 2)
(100, 2)
(100, 2)
(100, 2)


In [14]:
from sklearn.model_selection import train_test_split

In [15]:

x1_train, x1_test, y1_train, y1_test = train_test_split(
x1, y1, random_state=2020, test_size=0.2, shuffle = False
)
x1_val, x1_test, y1_val, y1_test = train_test_split(
x1_test, y1_test, random_state=2020, test_size=0.5, shuffle = False
)
x2_train, x2_test, y2_train, y2_test = train_test_split(
x2, y2, random_state=2020, test_size=0.2, shuffle = False
)
x2_val, x2_test, y2_val, y2_test = train_test_split(
x2_test, y2_test, random_state=2020, test_size=0.5, shuffle = False
)


In [16]:
# y3 데이터의 분리
y3_train, y3_test = train_test_split(
y3 , random_state=2020, test_size=0.2, shuffle=False
)
y3_val, y3_test = train_test_split(
y3_test , random_state=2020, test_size=0.5, shuffle=False)

In [17]:
from keras.models import Sequential, Model
from keras.layers import Dense, Input

Using TensorFlow backend.


In [18]:
input1 = Input(shape=(2,))
dense1 = Dense(100, activation='relu')(input1)
dense1 = Dense(30)(dense1)
dense1 = Dense(7)(dense1)

input2 = Input(shape=(2,))
dense2 = Dense(50, activation='relu')(input2)
dense2 = Dense(30)(dense2)
dense2 = Dense(7)(dense2)

In [19]:
from keras.layers.merge import concatenate

In [20]:
merge1 = concatenate([dense1, dense2])
middle1 = Dense(10)(merge1)
middle2 = Dense(5)(middle1)
middle3 = Dense(30)(middle2)

output1 = Dense(30)(middle3)
output1 = Dense(7)(output1)
output1 = Dense(2)(output1)

output2 = Dense(20)(middle3)
output2 = Dense(70)(output2)
output2 = Dense(2)(output2)

output3 = Dense(25)(middle3)
output3 = Dense(5)(output3)
output3 = Dense(2)(output3)

In [21]:
model = Model(inputs = [input1, input2],outputs = [output1, output2, output3])

In [22]:
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit([x1_train, x2_train], [y1_train, y2_train, y3_train],
          epochs=50, batch_size=1,
          validation_data=([x1_val, x2_val], [y1_val, y2_val, y3_val]))

Epoch 1/50
80/80 [==============================] - 0s 5ms/step - loss: 171182.3281 - dense_11_loss: 2603.6755 - dense_14_loss: 55979.8867 - dense_17_loss: 112598.7734 - dense_11_mse: 2603.6755 - dense_14_mse: 55979.8867 - dense_17_mse: 112598.7734 - val_loss: 2305.8284 - val_dense_11_loss: 618.9448 - val_dense_14_loss: 122.2047 - val_dense_17_loss: 1564.6788 - val_dense_11_mse: 618.9448 - val_dense_14_mse: 122.2047 - val_dense_17_mse: 1564.6788
Epoch 2/50
80/80 [==============================] - 0s 2ms/step - loss: 612.6964 - dense_11_loss: 212.8631 - dense_14_loss: 91.3340 - dense_17_loss: 308.4993 - dense_11_mse: 212.8631 - dense_14_mse: 91.3340 - dense_17_mse: 308.4993 - val_loss: 570.7881 - val_dense_11_loss: 389.0432 - val_dense_14_loss: 17.4343 - val_dense_17_loss: 164.3107 - val_dense_11_mse: 389.0432 - val_dense_14_mse: 17.4343 - val_dense_17_mse: 164.3107
Epoch 3/50
80/80 [==============================] - 0s 2ms/step - loss: 265.5972 - dense_11_loss: 122.8081 - dense_14_loss

Epoch 21/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3702 - dense_11_loss: 0.0807 - dense_14_loss: 0.1435 - dense_17_loss: 0.1460 - dense_11_mse: 0.0807 - dense_14_mse: 0.1435 - dense_17_mse: 0.1460 - val_loss: 0.7765 - val_dense_11_loss: 0.5543 - val_dense_14_loss: 0.1635 - val_dense_17_loss: 0.0588 - val_dense_11_mse: 0.5543 - val_dense_14_mse: 0.1635 - val_dense_17_mse: 0.0588
Epoch 22/50
80/80 [==============================] - 0s 2ms/step - loss: 0.5610 - dense_11_loss: 0.1734 - dense_14_loss: 0.1474 - dense_17_loss: 0.2402 - dense_11_mse: 0.1734 - dense_14_mse: 0.1474 - dense_17_mse: 0.2402 - val_loss: 0.2694 - val_dense_11_loss: 0.2173 - val_dense_14_loss: 0.0202 - val_dense_17_loss: 0.0318 - val_dense_11_mse: 0.2173 - val_dense_14_mse: 0.0202 - val_dense_17_mse: 0.0318
Epoch 23/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3324 - dense_11_loss: 0.0750 - dense_14_loss: 0.1241 - dense_17_loss: 0.1334 - dense_11_mse: 0.0750 - dense_14_mse:

80/80 [==============================] - 0s 2ms/step - loss: 12.7565 - dense_11_loss: 5.7630 - dense_14_loss: 3.1980 - dense_17_loss: 3.7955 - dense_11_mse: 5.7630 - dense_14_mse: 3.1980 - dense_17_mse: 3.7955 - val_loss: 13.4754 - val_dense_11_loss: 3.5821 - val_dense_14_loss: 4.4896 - val_dense_17_loss: 5.4037 - val_dense_11_mse: 3.5821 - val_dense_14_mse: 4.4896 - val_dense_17_mse: 5.4037
Epoch 42/50
80/80 [==============================] - 0s 2ms/step - loss: 5.7036 - dense_11_loss: 2.6004 - dense_14_loss: 1.4017 - dense_17_loss: 1.7015 - dense_11_mse: 2.6004 - dense_14_mse: 1.4017 - dense_17_mse: 1.7015 - val_loss: 2.2021 - val_dense_11_loss: 1.0197 - val_dense_14_loss: 0.6837 - val_dense_17_loss: 0.4987 - val_dense_11_mse: 1.0197 - val_dense_14_mse: 0.6837 - val_dense_17_mse: 0.4987
Epoch 43/50
80/80 [==============================] - 0s 2ms/step - loss: 1.2922 - dense_11_loss: 0.7441 - dense_14_loss: 0.2689 - dense_17_loss: 0.2791 - dense_11_mse: 0.7441 - dense_14_mse: 0.2689 - 

In [23]:
mse = model.evaluate([x1_test, x2_test],
[y1_test, y2_test, y3_test], batch_size=1)

y1_predict, y2_predict, y3_predict = model.predict([x1_test, x2_test])
print("y1 예측값 : \n", y1_predict,
      "\n y2 예측값 : \n", y2_predict, "\n y3 예측값 : \n", y3_predict)

10/10 [==============================] - 0s 1ms/step - loss: 41.5858 - dense_11_loss: 0.1751 - dense_14_loss: 20.3527 - dense_17_loss: 21.0580 - dense_11_mse: 0.1751 - dense_14_mse: 20.3527 - dense_17_mse: 21.0580
y1 예측값 : 
 [[ 91.24292  190.39621 ]
 [ 92.27597  191.43654 ]
 [ 93.309074 192.47693 ]
 [ 94.34214  193.5173  ]
 [ 95.37528  194.5577  ]
 [ 96.40843  195.59808 ]
 [ 97.4415   196.63849 ]
 [ 98.465904 197.6711  ]
 [ 99.48141  198.69566 ]
 [100.49689  199.72037 ]] 
 y2 예측값 : 
 [[588.7548  684.72534]
 [589.8062  685.7754 ]
 [590.8576  686.8255 ]
 [591.90894 687.8755 ]
 [592.9604  688.9257 ]
 [594.01166 689.97577]
 [595.0631  691.0259 ]
 [596.1125  692.07526]
 [597.16    693.1239 ]
 [598.2075  694.1725 ]] 
 y3 예측값 : 
 [[786.83136 885.5929 ]
 [787.8796  886.65106]
 [788.9277  887.7091 ]
 [789.97577 888.76733]
 [791.02405 889.82556]
 [792.0721  890.88385]
 [793.1203  891.94196]
 [794.16876 893.0025 ]
 [795.21716 894.0655 ]
 [796.2658  895.12854]]


In [24]:
x1_test

array([[ 91, 191],
       [ 92, 192],
       [ 93, 193],
       [ 94, 194],
       [ 95, 195],
       [ 96, 196],
       [ 97, 197],
       [ 98, 198],
       [ 99, 199],
       [100, 200]])

In [25]:
x2_test

array([[591, 691],
       [592, 692],
       [593, 693],
       [594, 694],
       [595, 695],
       [596, 696],
       [597, 697],
       [598, 698],
       [599, 699],
       [600, 700]])

In [28]:
y3_test

array([[791, 891],
       [792, 892],
       [793, 893],
       [794, 894],
       [795, 895],
       [796, 896],
       [797, 897],
       [798, 898],
       [799, 899],
       [800, 900]])