In [1]:
import numpy as np

In [2]:
dataset = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset) -1:
            break
        tmp_x, tmp_y = dataset[i:end_number], dataset[end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)


In [4]:
x, y = split_xy1(dataset, 4)
print(x, "\n", y)
print(x.shape)
print(y.shape)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
 [ 5  6  7  8  9 10]
(6, 4)
(6,)


In [5]:
x = x.reshape(x.shape[0], x.shape[1], 1)
print(x.shape)

(6, 4, 1)


In [6]:
x

array([[[1],
        [2],
        [3],
        [4]],

       [[2],
        [3],
        [4],
        [5]],

       [[3],
        [4],
        [5],
        [6]],

       [[4],
        [5],
        [6],
        [7]],

       [[5],
        [6],
        [7],
        [8]],

       [[6],
        [7],
        [8],
        [9]]])

In [7]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

Using TensorFlow backend.


In [8]:
model = Sequential()
model.add(LSTM(64, input_shape=(4, 1)))
model.add(Dense(1))

In [9]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 2ms/step - loss: 53.9032
Epoch 2/1000
1/1 [==============================] - 0s 997us/step - loss: 52.4976
Epoch 3/1000
1/1 [==============================] - 0s 998us/step - loss: 51.1049
Epoch 4/1000
1/1 [==============================] - 0s 7ms/step - loss: 49.7242
Epoch 5/1000
1/1 [==============================] - 0s 3ms/step - loss: 48.3551
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 46.9967
Epoch 7/1000
1/1 [==============================] - 0s 997us/step - loss: 45.6473
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 44.3056
Epoch 9/1000
1/1 [==============================] - 0s 0s/step - loss: 42.9704
Epoch 10/1000
1/1 [==============================] - 0s 996us/step - loss: 41.6410
Epoch 11/1000
1/1 [==============================] - 0s 4ms/step - loss: 40.3170
Epoch 12/1000
1/1 [==============================] - 0s 995us/step - loss: 38.9978
Epoch 13/1000
1/1 [=========

1/1 [==============================] - 0s 997us/step - loss: 0.6770
Epoch 102/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6694
Epoch 103/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6619
Epoch 104/1000
1/1 [==============================] - 0s 993us/step - loss: 0.6544
Epoch 105/1000
1/1 [==============================] - 0s 996us/step - loss: 0.6469
Epoch 106/1000
1/1 [==============================] - 0s 997us/step - loss: 0.6395
Epoch 107/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6320
Epoch 108/1000
1/1 [==============================] - 0s 997us/step - loss: 0.6245
Epoch 109/1000
1/1 [==============================] - 0s 997us/step - loss: 0.6169
Epoch 110/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6094
Epoch 111/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6017
Epoch 112/1000
1/1 [==============================] - 0s 997us/step - loss: 0.5941
Epoch 113/1000
1/1 [=========

Epoch 201/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2524
Epoch 202/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2512
Epoch 203/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2500
Epoch 204/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2488
Epoch 205/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2476
Epoch 206/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2465
Epoch 207/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2453
Epoch 208/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2442
Epoch 209/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.2431
Epoch 210/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2420
Epoch 211/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2410
Epoch 212/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2399
Epoch 213/1000
1/1 [=

1/1 [==============================] - 0s 2ms/step - loss: 0.1774
Epoch 302/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1768
Epoch 303/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1763
Epoch 304/1000
1/1 [==============================] - 0s 996us/step - loss: 0.1758
Epoch 305/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1752
Epoch 306/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1747
Epoch 307/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1741
Epoch 308/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1736
Epoch 309/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1730
Epoch 310/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1725
Epoch 311/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1719
Epoch 312/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1714
Epoch 313/1000
1/1 [=======

1/1 [==============================] - 0s 2ms/step - loss: 0.1237
Epoch 401/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1231
Epoch 402/1000
1/1 [==============================] - 0s 996us/step - loss: 0.1226
Epoch 403/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1220
Epoch 404/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.1215
Epoch 405/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1210
Epoch 406/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1204
Epoch 407/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1199
Epoch 408/1000
1/1 [==============================] - 0s 45ms/step - loss: 0.1193
Epoch 409/1000
1/1 [==============================] - 0s 996us/step - loss: 0.1188
Epoch 410/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1183
Epoch 411/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1177
Epoch 412/1000
1/1 [==========

1/1 [==============================] - 0s 3ms/step - loss: 0.0690
Epoch 501/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0685
Epoch 502/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0680
Epoch 503/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0674
Epoch 504/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0669
Epoch 505/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0663
Epoch 506/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0658
Epoch 507/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0653
Epoch 508/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0647
Epoch 509/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0642
Epoch 510/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0636
Epoch 511/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0631
Epoch 512/1000
1/1 [=====

1/1 [==============================] - 0s 996us/step - loss: 0.0233
Epoch 600/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0229
Epoch 601/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0226
Epoch 602/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0223
Epoch 603/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0220
Epoch 604/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0216
Epoch 605/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0213
Epoch 606/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0210
Epoch 607/1000
1/1 [==============================] - 0s 993us/step - loss: 0.0207
Epoch 608/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0204
Epoch 609/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0201
Epoch 610/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0198
Epoch 611/1000
1/1 [=======

1/1 [==============================] - 0s 997us/step - loss: 0.0049
Epoch 699/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0048
Epoch 700/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0047
Epoch 701/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0046
Epoch 702/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0046
Epoch 703/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 704/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0044
Epoch 705/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0044
Epoch 706/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 707/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.0042
Epoch 708/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0042
Epoch 709/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0041
Epoch 710/1000
1/1 [===============

1/1 [==============================] - 0s 2ms/step - loss: 0.0017
Epoch 798/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0017
Epoch 799/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0017
Epoch 800/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0016
Epoch 801/1000
1/1 [==============================] - 0s 994us/step - loss: 0.0016
Epoch 802/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0016
Epoch 803/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0016
Epoch 804/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0016
Epoch 805/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0016
Epoch 806/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0016
Epoch 807/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0016
Epoch 808/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0016
Epoch 809/1000
1/1 [=========

1/1 [==============================] - 0s 998us/step - loss: 0.0012
Epoch 897/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0012
Epoch 898/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012
Epoch 899/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0012
Epoch 900/1000
1/1 [==============================] - 0s 990us/step - loss: 0.0012
Epoch 901/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011
Epoch 902/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0011
Epoch 903/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0011
Epoch 904/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011
Epoch 905/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0011
Epoch 906/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0011
Epoch 907/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0011
Epoch 908/1000
1/1 [=======

1/1 [==============================] - 0s 997us/step - loss: 8.7656e-04
Epoch 994/1000
1/1 [==============================] - 0s 997us/step - loss: 8.7406e-04
Epoch 995/1000
1/1 [==============================] - 0s 995us/step - loss: 8.7154e-04
Epoch 996/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.6908e-04
Epoch 997/1000
1/1 [==============================] - 0s 997us/step - loss: 8.6659e-04
Epoch 998/1000
1/1 [==============================] - 0s 997us/step - loss: 8.6413e-04
Epoch 999/1000
1/1 [==============================] - 0s 998us/step - loss: 8.6169e-04
Epoch 1000/1000
1/1 [==============================] - 0s 997us/step - loss: 8.5926e-04


In [10]:
mse = model.evaluate(x, y )
print("mse : ", mse)

1/1 [==============================] - 0s 997us/step - loss: 8.5683e-04
mse :  0.0008568306802771986


In [11]:
x_pred = np.array([7, 8, 9, 10])
# x_pred = x_pred.reshape(1, x_pred.shape[0])
x_pred = x_pred.reshape(1, x_pred.shape[0], 1)

In [12]:
print(x_pred.shape)

(1, 4, 1)


In [13]:
y_pred = model.predict(x_pred)
print(y_pred)


[[10.62765]]


## MLP RNN(다:다)

In [15]:
def split_xy2(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i : x_end_number]
        tmp_y = dataset[x_end_number : y_end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [17]:
x, y = split_xy2(dataset, 4, 2)
print(x, "\n", y)
print(x.shape)
print(y.shape)
x = x.reshape(x.shape[0], x.shape[1], 1)
print(x.shape)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 
 [[ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]
(5, 4)
(5, 2)
(5, 4, 1)


In [18]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
#2. 모델 구성
model = Sequential()
model.add(LSTM(64, input_shape=(4, 1)))
model.add(Dense(2))

In [19]:
#3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 997us/step - loss: 55.3420
Epoch 2/1000
1/1 [==============================] - 0s 998us/step - loss: 54.3575
Epoch 3/1000
1/1 [==============================] - 0s 4ms/step - loss: 53.3803
Epoch 4/1000
1/1 [==============================] - 0s 996us/step - loss: 52.4098
Epoch 5/1000
1/1 [==============================] - 0s 998us/step - loss: 51.4453
Epoch 6/1000
1/1 [==============================] - 0s 997us/step - loss: 50.4857
Epoch 7/1000
1/1 [==============================] - 0s 3ms/step - loss: 49.5298
Epoch 8/1000
1/1 [==============================] - 0s 999us/step - loss: 48.5763
Epoch 9/1000
1/1 [==============================] - 0s 996us/step - loss: 47.6241
Epoch 10/1000
1/1 [==============================] - 0s 3ms/step - loss: 46.6717
Epoch 11/1000
1/1 [==============================] - 0s 3ms/step - loss: 45.7178
Epoch 12/1000
1/1 [==============================] - 0s 997us/step - loss: 44.7614
Epoch 13/1000
1/1 [==

1/1 [==============================] - 0s 998us/step - loss: 0.6648
Epoch 102/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6575
Epoch 103/1000
1/1 [==============================] - 0s 998us/step - loss: 0.6501
Epoch 104/1000
1/1 [==============================] - 0s 996us/step - loss: 0.6428
Epoch 105/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6355
Epoch 106/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6283
Epoch 107/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6211
Epoch 108/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6140
Epoch 109/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6070
Epoch 110/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6000
Epoch 111/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5931
Epoch 112/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5862
Epoch 113/1000
1/1 [=================

1/1 [==============================] - 0s 2ms/step - loss: 0.2227
Epoch 201/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.2211
Epoch 202/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2195
Epoch 203/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2179
Epoch 204/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2164
Epoch 205/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2149
Epoch 206/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2135
Epoch 207/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2121
Epoch 208/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.2107
Epoch 209/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2093
Epoch 210/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2080
Epoch 211/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2067
Epoch 212/1000
1/1 [=============

1/1 [==============================] - 0s 995us/step - loss: 0.1529
Epoch 300/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1525
Epoch 301/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1522
Epoch 302/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1518
Epoch 303/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1515
Epoch 304/1000
1/1 [==============================] - 0s 993us/step - loss: 0.1511
Epoch 305/1000
1/1 [==============================] - 0s 996us/step - loss: 0.1507
Epoch 306/1000
1/1 [==============================] - 0s 996us/step - loss: 0.1504
Epoch 307/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1500
Epoch 308/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1497
Epoch 309/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1493
Epoch 310/1000
1/1 [==============================] - 0s 994us/step - loss: 0.1490
Epoch 311/1000
1/1 [=========

1/1 [==============================] - 0s 997us/step - loss: 0.1194
Epoch 399/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1191
Epoch 400/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1188
Epoch 401/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1184
Epoch 402/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1181
Epoch 403/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1178
Epoch 404/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.1174
Epoch 405/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1171
Epoch 406/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1167
Epoch 407/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1164
Epoch 408/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1161
Epoch 409/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1157
Epoch 410/1000
1/1 [=======

1/1 [==============================] - 0s 996us/step - loss: 0.0819
Epoch 498/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0814
Epoch 499/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0810
Epoch 500/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0805
Epoch 501/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0801
Epoch 502/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0796
Epoch 503/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0791
Epoch 504/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0787
Epoch 505/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0782
Epoch 506/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0777
Epoch 507/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0772
Epoch 508/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0768
Epoch 509/1000
1/1 [=

1/1 [==============================] - 0s 997us/step - loss: 0.0293
Epoch 597/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0288
Epoch 598/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0283
Epoch 599/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0278
Epoch 600/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0273
Epoch 601/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0268
Epoch 602/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0264
Epoch 603/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0259
Epoch 604/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0255
Epoch 605/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0250
Epoch 606/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0246
Epoch 607/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0241
Epoch 608/1000
1/1 [=====

1/1 [==============================] - 0s 4ms/step - loss: 0.0053
Epoch 696/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0053
Epoch 697/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0052
Epoch 698/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0051
Epoch 699/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0051
Epoch 700/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0050
Epoch 701/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0050
Epoch 702/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 703/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0049
Epoch 704/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0048
Epoch 705/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0047
Epoch 706/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0047
Epoch 707/1000
1/1 [=========

Epoch 795/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0023
Epoch 796/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022
Epoch 797/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0022
Epoch 798/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0022
Epoch 799/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022
Epoch 800/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0022
Epoch 801/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022
Epoch 802/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0022
Epoch 803/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022
Epoch 804/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0021
Epoch 805/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0021
Epoch 806/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0021
Epoch 807/1000
1/1 [

Epoch 895/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0014
Epoch 896/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0014
Epoch 897/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0013
Epoch 898/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0013
Epoch 899/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0013
Epoch 900/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0013
Epoch 901/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0013
Epoch 902/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0013
Epoch 903/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0013
Epoch 904/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0013
Epoch 905/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0013
Epoch 906/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0013
Epoch 907/10

1/1 [==============================] - 0s 998us/step - loss: 9.6558e-04
Epoch 994/1000
1/1 [==============================] - 0s 997us/step - loss: 9.6250e-04
Epoch 995/1000
1/1 [==============================] - 0s 998us/step - loss: 9.5942e-04
Epoch 996/1000
1/1 [==============================] - 0s 998us/step - loss: 9.5637e-04
Epoch 997/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.5334e-04
Epoch 998/1000
1/1 [==============================] - 0s 997us/step - loss: 9.5030e-04
Epoch 999/1000
1/1 [==============================] - 0s 3ms/step - loss: 9.4730e-04
Epoch 1000/1000
1/1 [==============================] - 0s 998us/step - loss: 9.4429e-04


In [20]:
mse = model.evaluate(x, y )
print("mse : ", mse)
x_pred = np.array([6, 7, 8, 9])
x_pred = x_pred.reshape(1, x_pred.shape[0], 1)
# print(x_pred.shape)


1/1 [==============================] - 0s 997us/step - loss: 9.4131e-04
mse :  0.0009413057705387473


In [21]:
y_pred = model.predict(x_pred)
print(y_pred)

[[ 9.668809 10.518758]]


## MLP RNN(다:1)

In [22]:
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],
                    [21,22,23,24,25,26,27,28,29,30]])
print("dataset.shape : ", dataset.shape)

dataset.shape :  (3, 10)


In [23]:
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)


In [24]:
def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)


In [25]:
x, y = split_xy3(dataset, 3, 1)
print(x, "\n", y)
print(x.shape)
print(y.shape)

y = y.reshape(y.shape[0])
print(y.shape)

[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]

 [[ 8 18]
  [ 9 19]
  [10 20]]] 
 [[23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
(8, 3, 2)
(8, 1)
(8,)


In [26]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
model = Sequential()
model.add(LSTM(64, input_shape=(3, 2)))
model.add(Dense(1))

In [27]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 64)                17152     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 17,217
Trainable params: 17,217
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1)
#4. 평가, 예측



Epoch 1/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0342
Epoch 2/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0224
Epoch 3/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0118
Epoch 4/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0232
Epoch 5/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0146
Epoch 6/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0055
Epoch 7/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 8/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0087
Epoch 9/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 10/300
8/8 [==============================] - 0s 1ms/step - loss: 0.0033
Epoch 11/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0057
Epoch 12/300
8/8 [==============================] - 0s 1ms/step - loss: 0.0044
Epoch 13/300
8/8 [==============================] - 0s 2ms/st

8/8 [==============================] - 0s 2ms/step - loss: 0.0017
Epoch 104/300
8/8 [==============================] - 0s 2ms/step - loss: 7.7993e-04
Epoch 105/300
8/8 [==============================] - 0s 3ms/step - loss: 0.0017
Epoch 106/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0017
Epoch 107/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0010
Epoch 108/300
8/8 [==============================] - 0s 2ms/step - loss: 3.0105e-04
Epoch 109/300
8/8 [==============================] - 0s 2ms/step - loss: 1.8643e-04
Epoch 110/300
8/8 [==============================] - 0s 2ms/step - loss: 1.6827e-04
Epoch 111/300
8/8 [==============================] - 0s 3ms/step - loss: 3.0370e-04
Epoch 112/300
8/8 [==============================] - 0s 2ms/step - loss: 6.0972e-04
Epoch 113/300
8/8 [==============================] - 0s 2ms/step - loss: 2.2516e-04
Epoch 114/300
8/8 [==============================] - 0s 2ms/step - loss: 2.1744e-04
Epoch 115/300
8/8 [===

8/8 [==============================] - 0s 2ms/step - loss: 0.0081
Epoch 203/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0152
Epoch 204/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0144
Epoch 205/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0260
Epoch 206/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0138
Epoch 207/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0113
Epoch 208/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0254
Epoch 209/300
8/8 [==============================] - 0s 1ms/step - loss: 0.0234
Epoch 210/300
8/8 [==============================] - 0s 1ms/step - loss: 0.0086
Epoch 211/300
8/8 [==============================] - 0s 1ms/step - loss: 0.0045
Epoch 212/300
8/8 [==============================] - 0s 2ms/step - loss: 0.0076
Epoch 213/300
8/8 [==============================] - 0s 3ms/step - loss: 0.0052
Epoch 214/300
8/8 [==============================] - 0

In [30]:
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

8/8 [==============================] - 0s 998us/step - loss: 0.0024
mse :  0.0023811552673578262


In [31]:
x_pred = np.array([[9, 10, 11], [19, 20, 21]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])
print(x_pred.shape)

(1, 3, 2)


In [32]:
y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

[[30.333158]]


## MLP DNN(다:1)

In [33]:
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])

In [34]:
print("dataset.shape : ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)


In [35]:
def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1 # 수정
        if y_end_number > len(dataset): # 수정
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)


In [36]:
x, y = split_xy3(dataset, 3, 1)
print(x, "\n", y)
print(x.shape)
print(y.shape)
y = y.reshape(y.shape[0])
print(y.shape)

[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]

 [[ 8 18]
  [ 9 19]
  [10 20]]] 
 [[23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
(8, 3, 2)
(8, 1)
(8,)


In [39]:
x = x.reshape(x.shape[0], x.shape[1] * x.shape[2])
print(x.shape)

(8, 6)


In [37]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
model = Sequential()
# model.add(LSTM(64, input_shape=(3, 2)))
model.add(Dense(64, input_shape=(6, )))
model.add(Dense(1))

In [38]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 64)                448       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 65        
Total params: 513
Trainable params: 513
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1)

Epoch 1/300
8/8 [==============================] - 0s 997us/step - loss: 278.1403
Epoch 2/300
8/8 [==============================] - 0s 997us/step - loss: 119.4276
Epoch 3/300
8/8 [==============================] - 0s 2ms/step - loss: 35.0995
Epoch 4/300
8/8 [==============================] - 0s 2ms/step - loss: 12.3576
Epoch 5/300
8/8 [==============================] - 0s 873us/step - loss: 13.6110
Epoch 6/300
8/8 [==============================] - 0s 1ms/step - loss: 14.5108
Epoch 7/300
8/8 [==============================] - 0s 1ms/step - loss: 12.1851
Epoch 8/300
8/8 [==============================] - 0s 1ms/step - loss: 9.8106
Epoch 9/300
8/8 [==============================] - 0s 1ms/step - loss: 10.6749
Epoch 10/300
8/8 [==============================] - 0s 1ms/step - loss: 10.0477
Epoch 11/300
8/8 [==============================] - 0s 1ms/step - loss: 9.6507
Epoch 12/300
8/8 [==============================] - 0s 1ms/step - loss: 9.4497
Epoch 13/300
8/8 [==========================

8/8 [==============================] - 0s 1ms/step - loss: 0.0029
Epoch 105/300
8/8 [==============================] - 0s 1ms/step - loss: 0.0024
Epoch 106/300
8/8 [==============================] - 0s 747us/step - loss: 0.0025
Epoch 107/300
8/8 [==============================] - 0s 1ms/step - loss: 0.0022
Epoch 108/300
8/8 [==============================] - 0s 1ms/step - loss: 0.0021
Epoch 109/300
8/8 [==============================] - 0s 1ms/step - loss: 0.0013
Epoch 110/300
8/8 [==============================] - 0s 1ms/step - loss: 0.0012
Epoch 111/300
8/8 [==============================] - 0s 997us/step - loss: 7.5401e-04
Epoch 112/300
8/8 [==============================] - 0s 748us/step - loss: 6.7345e-04
Epoch 113/300
8/8 [==============================] - 0s 1ms/step - loss: 5.4511e-04
Epoch 114/300
8/8 [==============================] - 0s 997us/step - loss: 4.8939e-04
Epoch 115/300
8/8 [==============================] - 0s 623us/step - loss: 3.9404e-04
Epoch 116/300
8/8 [=====

8/8 [==============================] - 0s 1ms/step - loss: 6.6393e-11
Epoch 201/300
8/8 [==============================] - 0s 873us/step - loss: 6.4119e-11
Epoch 202/300
8/8 [==============================] - 0s 873us/step - loss: 5.6843e-11
Epoch 203/300
8/8 [==============================] - 0s 1ms/step - loss: 5.3660e-11
Epoch 204/300
8/8 [==============================] - 0s 499us/step - loss: 4.9567e-11
Epoch 205/300
8/8 [==============================] - 0s 872us/step - loss: 4.0473e-11
Epoch 206/300
8/8 [==============================] - 0s 1ms/step - loss: 4.0473e-11
Epoch 207/300
8/8 [==============================] - 0s 748us/step - loss: 4.3656e-11
Epoch 208/300
8/8 [==============================] - 0s 1ms/step - loss: 3.9108e-11
Epoch 209/300
8/8 [==============================] - 0s 997us/step - loss: 4.4565e-11
Epoch 210/300
8/8 [==============================] - 0s 623us/step - loss: 3.1378e-11
Epoch 211/300
8/8 [==============================] - 0s 1ms/step - loss: 2.2

8/8 [==============================] - 0s 997us/step - loss: 8.1855e-12
Epoch 296/300
8/8 [==============================] - 0s 1ms/step - loss: 6.3665e-12
Epoch 297/300
8/8 [==============================] - 0s 1ms/step - loss: 6.3665e-12
Epoch 298/300
8/8 [==============================] - 0s 622us/step - loss: 6.3665e-12
Epoch 299/300
8/8 [==============================] - 0s 1ms/step - loss: 6.3665e-12
Epoch 300/300
8/8 [==============================] - 0s 623us/step - loss: 6.3665e-12


In [41]:
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

8/8 [==============================] - 0s 748us/step - loss: 6.8212e-12
mse :  6.821210263296962e-12


In [42]:
x_pred = np.array([[9, 10, 11], [19, 20, 21]])
print(x_pred.shape)

x_pred = x_pred.reshape(1, x_pred.shape[0] * x_pred.shape[1])
print(x_pred.shape)

(2, 3)
(1, 6)


In [43]:
y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)


[[23.782112]]


## MLP DNN(다:다)

In [53]:
del model

In [44]:
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])

In [45]:
print("dataset.shape : ", dataset.shape)

dataset.shape :  (3, 10)


In [46]:
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)


[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)


In [47]:
def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)


In [48]:
x, y = split_xy3(dataset, 3, 2)
# print(x, "\n", y)
print(x.shape)
print(y.shape)

(7, 3, 2)
(7, 2)


In [50]:
x

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13]],

       [[ 2, 12],
        [ 3, 13],
        [ 4, 14]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 4, 14],
        [ 5, 15],
        [ 6, 16]],

       [[ 5, 15],
        [ 6, 16],
        [ 7, 17]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]],

       [[ 7, 17],
        [ 8, 18],
        [ 9, 19]]])

In [51]:
y

array([[23, 24],
       [24, 25],
       [25, 26],
       [26, 27],
       [27, 28],
       [28, 29],
       [29, 30]])

In [54]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
model = Sequential()
model.add(LSTM(64, input_shape=(3, 2)))
model.add(Dense(2))


In [55]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1)

Epoch 1/300
7/7 [==============================] - 0s 1ms/step - loss: 701.2582
Epoch 2/300
7/7 [==============================] - 0s 2ms/step - loss: 665.5663
Epoch 3/300
7/7 [==============================] - 0s 4ms/step - loss: 630.9018
Epoch 4/300
7/7 [==============================] - 0s 2ms/step - loss: 595.6131
Epoch 5/300
7/7 [==============================] - 0s 2ms/step - loss: 560.3748
Epoch 6/300
7/7 [==============================] - 0s 2ms/step - loss: 526.1741
Epoch 7/300
7/7 [==============================] - 0s 2ms/step - loss: 493.1819
Epoch 8/300
7/7 [==============================] - 0s 2ms/step - loss: 460.0769
Epoch 9/300
7/7 [==============================] - 0s 2ms/step - loss: 429.8047
Epoch 10/300
7/7 [==============================] - 0s 2ms/step - loss: 401.7683
Epoch 11/300
7/7 [==============================] - 0s 2ms/step - loss: 376.6638
Epoch 12/300
7/7 [==============================] - 0s 2ms/step - loss: 352.7983
Epoch 13/300
7/7 [===================

7/7 [==============================] - 0s 2ms/step - loss: 3.7338
Epoch 104/300
7/7 [==============================] - 0s 2ms/step - loss: 3.7234
Epoch 105/300
7/7 [==============================] - 0s 2ms/step - loss: 3.7147
Epoch 106/300
7/7 [==============================] - 0s 1ms/step - loss: 3.7166
Epoch 107/300
7/7 [==============================] - 0s 1ms/step - loss: 3.7108
Epoch 108/300
7/7 [==============================] - 0s 2ms/step - loss: 3.7022
Epoch 109/300
7/7 [==============================] - 0s 2ms/step - loss: 3.6980
Epoch 110/300
7/7 [==============================] - 0s 1ms/step - loss: 3.6963
Epoch 111/300
7/7 [==============================] - 0s 1ms/step - loss: 3.6858
Epoch 112/300
7/7 [==============================] - 0s 1ms/step - loss: 3.6812
Epoch 113/300
7/7 [==============================] - 0s 1ms/step - loss: 3.6755
Epoch 114/300
7/7 [==============================] - 0s 1ms/step - loss: 3.6736
Epoch 115/300
7/7 [==============================] - 0

Epoch 205/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0963
Epoch 206/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0958
Epoch 207/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0878
Epoch 208/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0883
Epoch 209/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0847
Epoch 210/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0818
Epoch 211/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0758
Epoch 212/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0750
Epoch 213/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0710
Epoch 214/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0700
Epoch 215/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0674
Epoch 216/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0688
Epoch 217/300
7/7 [=====================

In [56]:
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)
x_pred = np.array([[9, 10, 11], [19, 20, 21]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])
# print(x_pred.shape)

7/7 [==============================] - 0s 855us/step - loss: 0.0073
mse :  0.0073171257972717285


In [57]:
y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)


[[29.029861 29.940924]]


In [59]:
x_pred

array([[[ 9, 19],
        [10, 20],
        [11, 21]]])

## MLP DNN(다:다)

In [61]:
del model

In [62]:
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                   [11,12,13,14,15,16,17,18,19,20],
                   [21,22,23,24,25,26,27,28,29,30]])

In [63]:
print("dataset.shape : ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)


In [64]:
def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [65]:
x, y = split_xy3(dataset, 3, 2)
print(x.shape)
print(y.shape)

(7, 3, 2)
(7, 2)


In [66]:
x = x.reshape(x.shape[0], x.shape[1] * x.shape[2])
print(x.shape)

(7, 6)


In [67]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
model = Sequential()
# model.add(LSTM(64, input_shape=(3, 2)))
model.add(Dense(64, input_shape=(6, )))
model.add(Dense(2))

In [68]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1)

Epoch 1/300
7/7 [==============================] - 0s 2ms/step - loss: 518.4066
Epoch 2/300
7/7 [==============================] - 0s 1ms/step - loss: 346.4376
Epoch 3/300
7/7 [==============================] - 0s 1ms/step - loss: 205.7508
Epoch 4/300
7/7 [==============================] - 0s 998us/step - loss: 107.8023
Epoch 5/300
7/7 [==============================] - 0s 997us/step - loss: 47.9758
Epoch 6/300
7/7 [==============================] - 0s 855us/step - loss: 18.9662
Epoch 7/300
7/7 [==============================] - 0s 997us/step - loss: 8.0015
Epoch 8/300
7/7 [==============================] - 0s 855us/step - loss: 7.1316
Epoch 9/300
7/7 [==============================] - 0s 1ms/step - loss: 7.4482
Epoch 10/300
7/7 [==============================] - 0s 2ms/step - loss: 7.5613
Epoch 11/300
7/7 [==============================] - 0s 2ms/step - loss: 6.9987
Epoch 12/300
7/7 [==============================] - 0s 1ms/step - loss: 6.6624
Epoch 13/300
7/7 [=======================

7/7 [==============================] - 0s 1ms/step - loss: 0.3288
Epoch 104/300
7/7 [==============================] - 0s 997us/step - loss: 0.2996
Epoch 105/300
7/7 [==============================] - 0s 1ms/step - loss: 0.2830
Epoch 106/300
7/7 [==============================] - 0s 2ms/step - loss: 0.2787
Epoch 107/300
7/7 [==============================] - 0s 1ms/step - loss: 0.2563
Epoch 108/300
7/7 [==============================] - 0s 997us/step - loss: 0.2313
Epoch 109/300
7/7 [==============================] - 0s 1ms/step - loss: 0.2698
Epoch 110/300
7/7 [==============================] - 0s 1ms/step - loss: 0.2121
Epoch 111/300
7/7 [==============================] - 0s 1ms/step - loss: 0.1843
Epoch 112/300
7/7 [==============================] - 0s 1ms/step - loss: 0.2278
Epoch 113/300
7/7 [==============================] - 0s 1ms/step - loss: 0.1754
Epoch 114/300
7/7 [==============================] - 0s 1ms/step - loss: 0.1870
Epoch 115/300
7/7 [==============================]

7/7 [==============================] - 0s 1ms/step - loss: 5.5204e-05
Epoch 204/300
7/7 [==============================] - 0s 1ms/step - loss: 4.2906e-05
Epoch 205/300
7/7 [==============================] - 0s 1ms/step - loss: 4.1649e-05
Epoch 206/300
7/7 [==============================] - 0s 2ms/step - loss: 3.4533e-05
Epoch 207/300
7/7 [==============================] - 0s 1ms/step - loss: 3.1581e-05
Epoch 208/300
7/7 [==============================] - 0s 997us/step - loss: 2.8066e-05
Epoch 209/300
7/7 [==============================] - 0s 1ms/step - loss: 2.6404e-05
Epoch 210/300
7/7 [==============================] - 0s 997us/step - loss: 2.7286e-05
Epoch 211/300
7/7 [==============================] - 0s 2ms/step - loss: 1.9133e-05
Epoch 212/300
7/7 [==============================] - 0s 1ms/step - loss: 1.7694e-05
Epoch 213/300
7/7 [==============================] - 0s 1ms/step - loss: 1.4094e-05
Epoch 214/300
7/7 [==============================] - 0s 1ms/step - loss: 1.3532e-05
Ep

7/7 [==============================] - 0s 1ms/step - loss: 1.2863e-10
Epoch 300/300
7/7 [==============================] - 0s 1ms/step - loss: 1.1642e-10


In [69]:
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)
x_pred = np.array([[9, 10, 11], [19, 20, 21]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0] * x_pred.shape[1])
print(x_pred.shape)

7/7 [==============================] - 0s 570us/step - loss: 1.0836e-10
mse :  1.0835980029932912e-10
(1, 6)


In [70]:

y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)


[[31.000017 32.000027]]


In [71]:
x_pred

array([[ 9, 19, 10, 20, 11, 21]])

## RNN 모델(다:다)

In [79]:
del model

In [72]:
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                   [11,12,13,14,15,16,17,18,19,20],
                   [21,22,23,24,25,26,27,28,29,30]])

In [73]:
print("dataset.shape : ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)


In [75]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :]
        tmp_y = dataset[x_end_number:y_end_number, :]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [76]:
x, y = split_xy5(dataset, 3, 1)
print(x, "\n", y)
print(x.shape)
print(y.shape)
y = y.reshape(y.shape[0], y.shape[2])
print(y.shape)

[[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]

 [[ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]] 
 [[[ 4 14 24]]

 [[ 5 15 25]]

 [[ 6 16 26]]

 [[ 7 17 27]]

 [[ 8 18 28]]

 [[ 9 19 29]]

 [[10 20 30]]]
(7, 3, 3)
(7, 1, 3)
(7, 3)


In [80]:
model = Sequential()
model.add(LSTM(64, input_shape=(3, 3)))
model.add(Dense(3))

In [81]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1)


Epoch 1/300
7/7 [==============================] - 0s 2ms/step - loss: 344.1444
Epoch 2/300
7/7 [==============================] - 0s 2ms/step - loss: 326.9207
Epoch 3/300
7/7 [==============================] - 0s 2ms/step - loss: 311.5982
Epoch 4/300
7/7 [==============================] - 0s 2ms/step - loss: 297.0262
Epoch 5/300
7/7 [==============================] - 0s 2ms/step - loss: 282.6825
Epoch 6/300
7/7 [==============================] - 0s 2ms/step - loss: 265.9078
Epoch 7/300
7/7 [==============================] - 0s 2ms/step - loss: 249.1835
Epoch 8/300
7/7 [==============================] - 0s 2ms/step - loss: 230.4951
Epoch 9/300
7/7 [==============================] - 0s 2ms/step - loss: 211.1189
Epoch 10/300
7/7 [==============================] - 0s 2ms/step - loss: 194.3901
Epoch 11/300
7/7 [==============================] - 0s 2ms/step - loss: 179.7950
Epoch 12/300
7/7 [==============================] - 0s 2ms/step - loss: 166.0322
Epoch 13/300
7/7 [===================

Epoch 104/300
7/7 [==============================] - 0s 2ms/step - loss: 1.3824
Epoch 105/300
7/7 [==============================] - 0s 2ms/step - loss: 1.5889
Epoch 106/300
7/7 [==============================] - 0s 2ms/step - loss: 1.4914
Epoch 107/300
7/7 [==============================] - 0s 2ms/step - loss: 1.1909
Epoch 108/300
7/7 [==============================] - 0s 2ms/step - loss: 1.2683
Epoch 109/300
7/7 [==============================] - 0s 2ms/step - loss: 1.1497
Epoch 110/300
7/7 [==============================] - 0s 2ms/step - loss: 1.0850
Epoch 111/300
7/7 [==============================] - 0s 2ms/step - loss: 1.0110
Epoch 112/300
7/7 [==============================] - 0s 2ms/step - loss: 0.9883
Epoch 113/300
7/7 [==============================] - 0s 2ms/step - loss: 0.9320
Epoch 114/300
7/7 [==============================] - 0s 2ms/step - loss: 0.8646
Epoch 115/300
7/7 [==============================] - 0s 2ms/step - loss: 0.7874
Epoch 116/300
7/7 [=====================

7/7 [==============================] - 0s 2ms/step - loss: 0.0425
Epoch 207/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0437
Epoch 208/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0400
Epoch 209/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0379
Epoch 210/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0400
Epoch 211/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0366
Epoch 212/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0363
Epoch 213/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0366
Epoch 214/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0333
Epoch 215/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0354
Epoch 216/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0424
Epoch 217/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0434
Epoch 218/300
7/7 [==============================] - 0

In [82]:
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

7/7 [==============================] - 0s 1ms/step - loss: 0.0094
mse :  0.009408154524862766


In [83]:
x_pred = np.array([[8, 9, 10],[18, 19, 20], [28, 29, 30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])
print(x_pred)
print(x_pred.shape)
y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

[[[ 8 18 28]
  [ 9 19 29]
  [10 20 30]]]
(1, 3, 3)
[[10.276269 20.25333  29.971848]]


## 이전 RNN을 DNN으로

In [86]:
del model

In [84]:
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],    
                    [21,22,23,24,25,26,27,28,29,30]])

In [85]:
print("dataset.shape : ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)


In [87]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :]
        tmp_y = dataset[x_end_number:y_end_number, :]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [88]:
x, y = split_xy5(dataset, 3, 1)
print(x, "\n", y)
print(x.shape)
print(y.shape)

[[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]

 [[ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]] 
 [[[ 4 14 24]]

 [[ 5 15 25]]

 [[ 6 16 26]]

 [[ 7 17 27]]

 [[ 8 18 28]]

 [[ 9 19 29]]

 [[10 20 30]]]
(7, 3, 3)
(7, 1, 3)


In [89]:
y = y.reshape(y.shape[0], y.shape[2])
print(y.shape)

(7, 3)


In [90]:
x = x.reshape(x.shape[0], x.shape[1] * x.shape[2])
print(x.shape)

(7, 9)


In [91]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
model = Sequential()
# model.add(LSTM(64, input_shape=(3, 3)))
model.add(Dense(64, input_shape=(9,)))
model.add(Dense(3))

In [92]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1)

Epoch 1/300
7/7 [==============================] - 0s 859us/step - loss: 330.8246
Epoch 2/300
7/7 [==============================] - 0s 1ms/step - loss: 123.3718
Epoch 3/300
7/7 [==============================] - 0s 1ms/step - loss: 29.0966
Epoch 4/300
7/7 [==============================] - 0s 570us/step - loss: 2.1165
Epoch 5/300
7/7 [==============================] - 0s 839us/step - loss: 6.2573
Epoch 6/300
7/7 [==============================] - 0s 2ms/step - loss: 8.3225
Epoch 7/300
7/7 [==============================] - 0s 712us/step - loss: 4.1088
Epoch 8/300
7/7 [==============================] - 0s 855us/step - loss: 1.7367
Epoch 9/300
7/7 [==============================] - 0s 2ms/step - loss: 1.6375
Epoch 10/300
7/7 [==============================] - 0s 2ms/step - loss: 1.6131
Epoch 11/300
7/7 [==============================] - 0s 1ms/step - loss: 1.2835
Epoch 12/300
7/7 [==============================] - 0s 855us/step - loss: 1.1133
Epoch 13/300
7/7 [==========================

7/7 [==============================] - 0s 998us/step - loss: 0.0147
Epoch 104/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0117
Epoch 105/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0148
Epoch 106/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0100
Epoch 107/300
7/7 [==============================] - 0s 997us/step - loss: 0.0105
Epoch 108/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0123
Epoch 109/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0070
Epoch 110/300
7/7 [==============================] - 0s 712us/step - loss: 0.0088
Epoch 111/300
7/7 [==============================] - 0s 997us/step - loss: 0.0074
Epoch 112/300
7/7 [==============================] - 0s 1ms/step - loss: 0.0078
Epoch 113/300
7/7 [==============================] - 0s 3ms/step - loss: 0.0048
Epoch 114/300
7/7 [==============================] - 0s 2ms/step - loss: 0.0056
Epoch 115/300
7/7 [===========================

7/7 [==============================] - 0s 4ms/step - loss: 2.9941e-07
Epoch 202/300
7/7 [==============================] - 0s 997us/step - loss: 3.3066e-07
Epoch 203/300
7/7 [==============================] - 0s 1ms/step - loss: 3.9096e-07
Epoch 204/300
7/7 [==============================] - 0s 1ms/step - loss: 2.9203e-07
Epoch 205/300
7/7 [==============================] - 0s 1ms/step - loss: 1.9908e-07
Epoch 206/300
7/7 [==============================] - 0s 2ms/step - loss: 2.1645e-07
Epoch 207/300
7/7 [==============================] - 0s 1ms/step - loss: 2.4882e-07
Epoch 208/300
7/7 [==============================] - 0s 1ms/step - loss: 2.1691e-07
Epoch 209/300
7/7 [==============================] - 0s 996us/step - loss: 1.5295e-07
Epoch 210/300
7/7 [==============================] - 0s 1ms/step - loss: 1.4758e-07
Epoch 211/300
7/7 [==============================] - 0s 1ms/step - loss: 6.2070e-08
Epoch 212/300
7/7 [==============================] - 0s 1ms/step - loss: 7.4710e-08
Ep

7/7 [==============================] - 0s 2ms/step - loss: 9.9070e-12
Epoch 299/300
7/7 [==============================] - 0s 712us/step - loss: 9.7338e-12
Epoch 300/300
7/7 [==============================] - 0s 1ms/step - loss: 9.4631e-12


In [93]:
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

7/7 [==============================] - 0s 712us/step - loss: 1.0340e-11
mse :  1.0340088160698535e-11


In [94]:
x_pred = np.array([[8, 9, 10],[18, 19, 20], [28, 29, 30]])
x_pred = np.transpose(x_pred)
# x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])
x_pred = x_pred.reshape(1, x_pred.shape[0] * x_pred.shape[1]) # 수정
print(x_pred)
print(x_pred.shape)
y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

[[ 8 18 28  9 19 29 10 20 30]]
(1, 9)
[[11.000001 21.000006 31.000004]]


## RNN(다:다)

In [95]:
del model

In [96]:
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],
                    [21,22,23,24,25,26,27,28,29,30]])

In [97]:
print("dataset.shape : ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)


In [98]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 수정
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :] # 수정
        tmp_y = dataset[x_end_number:y_end_number, :] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [99]:
x, y = split_xy5(dataset, 3, 2)
print(x, "\n", y)
print(x.shape)
print(y.shape)

[[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]] 
 [[[ 4 14 24]
  [ 5 15 25]]

 [[ 5 15 25]
  [ 6 16 26]]

 [[ 6 16 26]
  [ 7 17 27]]

 [[ 7 17 27]
  [ 8 18 28]]

 [[ 8 18 28]
  [ 9 19 29]]

 [[ 9 19 29]
  [10 20 30]]]
(6, 3, 3)
(6, 2, 3)


In [100]:
y = y.reshape(y.shape[0], y.shape[1] * y.shape[2])
print(y.shape)

(6, 6)


In [105]:
model = Sequential()
model.add(LSTM(64, input_shape=(3, 3)))
model.add(Dense(20))
model.add(Dense(10))
model.add(Dense(6))

In [106]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1)

Epoch 1/300
6/6 [==============================] - 0s 2ms/step - loss: 358.4441
Epoch 2/300
6/6 [==============================] - 0s 3ms/step - loss: 340.9310
Epoch 3/300
6/6 [==============================] - 0s 2ms/step - loss: 321.0374
Epoch 4/300
6/6 [==============================] - 0s 2ms/step - loss: 297.6510
Epoch 5/300
6/6 [==============================] - 0s 3ms/step - loss: 266.7603
Epoch 6/300
6/6 [==============================] - 0s 2ms/step - loss: 228.9291
Epoch 7/300
6/6 [==============================] - 0s 2ms/step - loss: 185.6398
Epoch 8/300
6/6 [==============================] - 0s 2ms/step - loss: 139.7794
Epoch 9/300
6/6 [==============================] - 0s 2ms/step - loss: 99.3711
Epoch 10/300
6/6 [==============================] - 0s 2ms/step - loss: 69.4251
Epoch 11/300
6/6 [==============================] - 0s 2ms/step - loss: 42.9890
Epoch 12/300
6/6 [==============================] - 0s 2ms/step - loss: 24.1436
Epoch 13/300
6/6 [=======================

6/6 [==============================] - 0s 1ms/step - loss: 0.0414
Epoch 105/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0365
Epoch 106/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0426
Epoch 107/300
6/6 [==============================] - 0s 3ms/step - loss: 0.0287
Epoch 108/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0323
Epoch 109/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0216
Epoch 110/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0312
Epoch 111/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0301
Epoch 112/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0264
Epoch 113/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0312
Epoch 114/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0433
Epoch 115/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0309
Epoch 116/300
6/6 [==============================] - 0

6/6 [==============================] - 0s 2ms/step - loss: 0.0013
Epoch 207/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0015
Epoch 208/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0016
Epoch 209/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0030
Epoch 210/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0021
Epoch 211/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 212/300
6/6 [==============================] - 0s 3ms/step - loss: 0.0074
Epoch 213/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0068
Epoch 214/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0181
Epoch 215/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0117
Epoch 216/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0081
Epoch 217/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0216
Epoch 218/300
6/6 [==============================] - 0

In [107]:
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

6/6 [==============================] - 0s 2ms/step - loss: 0.0053
mse :  0.005305586848407984


In [108]:
x_pred = np.array([[8, 9, 10],[18, 19, 20], [28, 29, 30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])
# print(x_pred)
# print(x_pred.shape)
y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

[[ 9.914324 20.084906 30.082035 11.027278 21.071476 31.017641]]


In [109]:
x_pred

array([[[ 8, 18, 28],
        [ 9, 19, 29],
        [10, 20, 30]]])

## DNN(다:다)

In [114]:
del model 

In [110]:
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                   [11,12,13,14,15,16,17,18,19,20],
                   [21,22,23,24,25,26,27,28,29,30]])

In [111]:
print("dataset.shape : ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)


dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)


In [112]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 수정
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :] # 수정
        tmp_y = dataset[x_end_number:y_end_number, :] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)


In [113]:
x, y = split_xy5(dataset, 3, 2)

x = x.reshape(x.shape[0], x.shape[1] * x.shape[2])
print(x.shape)
y = y.reshape(y.shape[0], y.shape[1] * y.shape[2])
print(y.shape)

(6, 9)
(6, 6)


In [122]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
model = Sequential()
# model.add(LSTM(64, input_shape=(3, 3)))
model.add(Dense(64, input_shape=(9, )))
model.add(Dense(30))
model.add(Dense(10))
model.add(Dense(6))

In [123]:
#3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1)

#4. 평가, 예측
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

Epoch 1/300
6/6 [==============================] - 0s 1ms/step - loss: 412.1046
Epoch 2/300
6/6 [==============================] - 0s 997us/step - loss: 243.6871
Epoch 3/300
6/6 [==============================] - 0s 1ms/step - loss: 187.6600
Epoch 4/300
6/6 [==============================] - 0s 997us/step - loss: 134.5686
Epoch 5/300
6/6 [==============================] - 0s 831us/step - loss: 92.4201
Epoch 6/300
6/6 [==============================] - 0s 1ms/step - loss: 59.5564
Epoch 7/300
6/6 [==============================] - 0s 998us/step - loss: 30.8419
Epoch 8/300
6/6 [==============================] - 0s 1ms/step - loss: 12.9380
Epoch 9/300
6/6 [==============================] - 0s 997us/step - loss: 3.6117
Epoch 10/300
6/6 [==============================] - 0s 831us/step - loss: 1.9596
Epoch 11/300
6/6 [==============================] - 0s 1ms/step - loss: 2.9153
Epoch 12/300
6/6 [==============================] - 0s 1ms/step - loss: 2.5307
Epoch 13/300
6/6 [===================

6/6 [==============================] - 0s 998us/step - loss: 0.0660
Epoch 104/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0711
Epoch 105/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0656
Epoch 106/300
6/6 [==============================] - 0s 998us/step - loss: 0.0692
Epoch 107/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0524
Epoch 108/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0755
Epoch 109/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0584
Epoch 110/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0530
Epoch 111/300
6/6 [==============================] - 0s 831us/step - loss: 0.0556
Epoch 112/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0621
Epoch 113/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0497
Epoch 114/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0580
Epoch 115/300
6/6 [=============================

6/6 [==============================] - 0s 1ms/step - loss: 0.0018
Epoch 205/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0016
Epoch 206/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0016
Epoch 207/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0018
Epoch 208/300
6/6 [==============================] - 0s 2ms/step - loss: 0.0015
Epoch 209/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0012
Epoch 210/300
6/6 [==============================] - 0s 1ms/step - loss: 0.0012
Epoch 211/300
6/6 [==============================] - 0s 3ms/step - loss: 0.0012
Epoch 212/300
6/6 [==============================] - 0s 997us/step - loss: 0.0015
Epoch 213/300
6/6 [==============================] - 0s 1ms/step - loss: 8.9310e-04
Epoch 214/300
6/6 [==============================] - 0s 1ms/step - loss: 9.8418e-04
Epoch 215/300
6/6 [==============================] - 0s 2ms/step - loss: 9.2255e-04
Epoch 216/300
6/6 [=====================

6/6 [==============================] - 0s 997us/step - loss: 3.6088e-06
mse :  3.6087812986806966e-06


In [124]:
x_pred = np.array([[8, 9, 10],[18, 19, 20], [28, 29, 30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0] * x_pred.shape[1])
print(x_pred)
print(x_pred.shape)
y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

[[ 8 18 28  9 19 29 10 20 30]]
(1, 9)
[[10.996607 21.00312  31.00742  12.001743 21.99259  32.004272]]


In [125]:
x_pred

array([[ 8, 18, 28,  9, 19, 29, 10, 20, 30]])