In [1]:
import numpy as np
x1 = np.array([range(1, 101), range(101, 201)])
y1 = np.array([range(1, 101), range(101, 201)])
x2 = np.array([range(501, 601), range(601, 701)])
y2 = np.array([range(501, 601), range(601, 701)])
print(x1.shape)
print(x2.shape)
print(y1.shape)
print(y2.shape)


(2, 100)
(2, 100)
(2, 100)
(2, 100)


In [2]:
x1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
        166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 17

In [3]:
y1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
        166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 17

In [4]:
x1 = np.transpose(x1)
y1 = np.transpose(y1)
x2 = np.transpose(x2)
y2 = np.transpose(y2)

In [7]:
print(x1.shape)
print(x2.shape)
print(y1.shape)
print(y2.shape)

(100, 2)
(100, 2)
(100, 2)
(100, 2)


In [8]:
from sklearn.model_selection import train_test_split

x1_train, x1_test, y1_train, y1_test = train_test_split(
x1, y1, random_state=66, test_size=0.2, shuffle = False
)
x1_val, x1_test, y1_val, y1_test = train_test_split(
x1_test, y1_test, random_state=66, test_size=0.5, shuffle = False
)
x2_train, x2_test, y2_train, y2_test = train_test_split(
x2, y2, random_state=66, test_size=0.2, shuffle = False
)
x2_val, x2_test, y2_val, y2_test = train_test_split(
x2_test, y2_test, random_state=66, test_size=0.5, shuffle = False
)

In [9]:
print('x2_train.shape : ', x2_train.shape)
print('x2_val.shape : ', x2_val.shape)
print('x2_test.shape : ', x2_test.shape)

x2_train.shape :  (80, 2)
x2_val.shape :  (10, 2)
x2_test.shape :  (10, 2)


In [10]:
from keras.models import Sequential, Model
from keras.layers import Dense, Input

Using TensorFlow backend.


In [20]:
# model = Sequential()
input1 = Input(shape=(2,))
dense1 = Dense(100, activation='relu')(input1)
dense1 = Dense(50)(dense1)
dense1 = Dense(7)(dense1)

input2 = Input(shape=(2,))
dense2 = Dense(100, activation='relu')(input2)
dense2 = Dense(50)(dense2)
dense2 = Dense(7)(dense2)

In [21]:
from keras.layers.merge import concatenate
merge1 = concatenate([dense1, dense2])
middle1 = Dense(50)(merge1)
middle2 = Dense(5)(middle1)
middle3 = Dense(30)(middle2)

output1 = Dense(50)(middle3)
output1 = Dense(7)(output1)
output1 = Dense(2)(output1)

output2 = Dense(100)(middle3)
output2 = Dense(70)(output2)
output2 = Dense(2)(output2)

model = Model(inputs = [input1, input2],
outputs = [output1, output2]
)

In [22]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
input_4 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
dense_15 (Dense)                (None, 100)          300         input_3[0][0]                    
__________________________________________________________________________________________________
dense_18 (Dense)                (None, 100)          300         input_4[0][0]                    
____________________________________________________________________________________________

In [23]:
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit([x1_train, x2_train], [y1_train, y2_train],
epochs=50, batch_size=1,
validation_data=([x1_val, x2_val] , [y1_val, y2_val]))

Epoch 1/50
80/80 [==============================] - 0s 4ms/step - loss: 28178.6445 - dense_26_loss: 1817.6400 - dense_29_loss: 26361.0000 - dense_26_mse: 1817.6400 - dense_29_mse: 26361.0000 - val_loss: 1926.2692 - val_dense_26_loss: 1450.2247 - val_dense_29_loss: 476.0443 - val_dense_26_mse: 1450.2247 - val_dense_29_mse: 476.0443
Epoch 2/50
80/80 [==============================] - 0s 2ms/step - loss: 457.8135 - dense_26_loss: 399.4855 - dense_29_loss: 58.3281 - dense_26_mse: 399.4855 - dense_29_mse: 58.3281 - val_loss: 1385.6598 - val_dense_26_loss: 1249.3362 - val_dense_29_loss: 136.3236 - val_dense_26_mse: 1249.3362 - val_dense_29_mse: 136.3236
Epoch 3/50
80/80 [==============================] - 0s 1ms/step - loss: 566.7811 - dense_26_loss: 529.5433 - dense_29_loss: 37.2378 - dense_26_mse: 529.5433 - dense_29_mse: 37.2378 - val_loss: 2392.7620 - val_dense_26_loss: 2218.4932 - val_dense_29_loss: 174.2687 - val_dense_26_mse: 2218.4932 - val_dense_29_mse: 174.2687
Epoch 4/50
80/80 [===

Epoch 28/50
80/80 [==============================] - 0s 1ms/step - loss: 2.7668 - dense_26_loss: 1.3410 - dense_29_loss: 1.4258 - dense_26_mse: 1.3410 - dense_29_mse: 1.4258 - val_loss: 0.2843 - val_dense_26_loss: 0.0843 - val_dense_29_loss: 0.2000 - val_dense_26_mse: 0.0843 - val_dense_29_mse: 0.2000
Epoch 29/50
80/80 [==============================] - 0s 2ms/step - loss: 1.3222 - dense_26_loss: 0.9884 - dense_29_loss: 0.3338 - dense_26_mse: 0.9884 - dense_29_mse: 0.3338 - val_loss: 0.3261 - val_dense_26_loss: 0.3013 - val_dense_29_loss: 0.0248 - val_dense_26_mse: 0.3013 - val_dense_29_mse: 0.0248
Epoch 30/50
80/80 [==============================] - 0s 1ms/step - loss: 0.6666 - dense_26_loss: 0.5358 - dense_29_loss: 0.1307 - dense_26_mse: 0.5358 - dense_29_mse: 0.1307 - val_loss: 0.2213 - val_dense_26_loss: 0.0987 - val_dense_29_loss: 0.1226 - val_dense_26_mse: 0.0987 - val_dense_29_mse: 0.1226
Epoch 31/50
80/80 [==============================] - 0s 1ms/step - loss: 0.3525 - dense_26_

In [24]:
mse = model.evaluate([x1_test, x2_test],
                     [y1_test, y2_test], batch_size=1)

10/10 [==============================] - 0s 997us/step - loss: 10.4369 - dense_26_loss: 10.2433 - dense_29_loss: 0.1935 - dense_26_mse: 10.2433 - dense_29_mse: 0.1935


In [25]:
print("mse : ", mse)
y1_predict, y2_predict = model.predict([x1_test, x2_test])
print("y1 예측값 : \n", y1_predict, "\n y2 예측값 : \n", y2_predict)

mse :  [10.436877250671387, 10.243337631225586, 0.19354113936424255, 10.243337631225586, 0.19354113936424255]
y1 예측값 : 
 [[ 88.04202  188.58203 ]
 [ 88.92961  189.49062 ]
 [ 89.81724  190.39925 ]
 [ 90.70483  191.30782 ]
 [ 91.59242  192.21643 ]
 [ 92.47309  193.1197  ]
 [ 93.339485 194.01198 ]
 [ 94.205894 194.90427 ]
 [ 95.07227  195.79655 ]
 [ 95.93869  196.68883 ]] 
 y2 예측값 : 
 [[591.5147  691.05524]
 [592.5254  692.08905]
 [593.5362  693.1232 ]
 [594.54694 694.15704]
 [595.5578  695.1912 ]
 [596.571   696.2277 ]
 [597.58905 697.2689 ]
 [598.6071  698.31036]
 [599.6252  699.35175]
 [600.6433  700.393  ]]


In [26]:
x1_test

array([[ 91, 191],
       [ 92, 192],
       [ 93, 193],
       [ 94, 194],
       [ 95, 195],
       [ 96, 196],
       [ 97, 197],
       [ 98, 198],
       [ 99, 199],
       [100, 200]])

In [27]:
x2_test

array([[591, 691],
       [592, 692],
       [593, 693],
       [594, 694],
       [595, 695],
       [596, 696],
       [597, 697],
       [598, 698],
       [599, 699],
       [600, 700]])