In [1]:
import numpy as np
x1 = np.array([range(100), range(311,411), range(100)])
x2 = np.array([range(101,201), range(311,411), range(101,201)])
y = np.array([range(501,601)]) #, range(711,811), range(100)]

In [2]:
x1.shape

(3, 100)

In [3]:
x1

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99],
       [311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323,
        324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336,
        337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349,
        350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362,
        363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375,
        376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 38

In [4]:
x2

array([[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
        166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
        179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
        192, 193, 194, 195, 196, 197, 198, 199, 200],
       [311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323,
        324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336,
        337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349,
        350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362,
        363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375,
        376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 38

In [5]:
y

array([[501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
        514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
        527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
        540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
        553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
        566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
        579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
        592, 593, 594, 595, 596, 597, 598, 599, 600]])

In [6]:
x1 = np.transpose(x1)
y = np.transpose(y)
x2 = np.transpose(x2)

In [7]:
from sklearn.model_selection import train_test_split

x1_train, x1_test, y_train, y_test = train_test_split(
x1, y, random_state=66, test_size=0.4, shuffle=False
)

x1_val, x1_test, y_val, y_test = train_test_split(
x1_test, y_test, random_state=66, test_size=0.5, shuffle=False
)

x2_train, x2_test = train_test_split(
x2, random_state=66, test_size=0.4, shuffle=False
)

x2_val, x2_test= train_test_split(
x2_test, random_state=66, test_size=0.5, shuffle = False
)

In [8]:
from keras.models import Sequential, Model
from keras.layers import Dense, Input

Using TensorFlow backend.


In [10]:
input1 = Input(shape=(3,))
dense1 = Dense(100, activation='relu')(input1)
dense1_2 = Dense(30)(dense1)
dense1_3 = Dense(7)(dense1_2)

In [11]:
input2 = Input(shape=(3,))
dense2 = Dense(50, activation='relu')(input2)
dense2_2 = Dense(7)(dense2)

In [12]:
from keras.layers.merge import concatenate
merge1 = concatenate([dense1_3, dense2_2])

In [13]:
merge1

<tf.Tensor 'concatenate_1/concat:0' shape=(?, 14) dtype=float32>

In [14]:
model1 = Dense(10)(merge1)
model2 = Dense(5)(model1)
output = Dense(1)(model2)

In [15]:
model = Model(inputs = [input1, input2], outputs = output)
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 3)            0                                            
__________________________________________________________________________________________________
dense_4 (Dense)                 (None, 100)          400         input_2[0][0]                    
__________________________________________________________________________________________________
input_3 (InputLayer)            (None, 3)            0                                            
__________________________________________________________________________________________________
dense_5 (Dense)                 (None, 30)           3030        dense_4[0][0]                    
____________________________________________________________________________________________

In [16]:
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit([x1_train, x2_train], y_train,
epochs=100, batch_size=1,
validation_data=([x1_val, x2_val] , y_val))

#4. 평가 예측
mse = model.evaluate([x1_test, x2_test],
y_test, batch_size=1)
print("mse : ", mse)

y_predict = model.predict([x1_test, x2_test])
for i in range(len(y_predict)):
    print(y_test[i], y_predict[i])

Instructions for updating:
Use tf.cast instead.
Train on 60 samples, validate on 20 samples
Epoch 1/100
60/60 [==============================] - 1s 9ms/step - loss: 19825.8266 - mse: 19825.8223 - val_loss: 4010.8875 - val_mse: 4010.8875
Epoch 2/100
60/60 [==============================] - 0s 1ms/step - loss: 295.4706 - mse: 295.4707 - val_loss: 702.1355 - val_mse: 702.1356
Epoch 3/100
60/60 [==============================] - 0s 981us/step - loss: 151.8256 - mse: 151.8256 - val_loss: 742.3145 - val_mse: 742.3146
Epoch 4/100
60/60 [==============================] - 0s 931us/step - loss: 47.3973 - mse: 47.3973 - val_loss: 167.2989 - val_mse: 167.2989
Epoch 5/100
60/60 [==============================] - 0s 931us/step - loss: 9.7509 - mse: 9.7509 - val_loss: 109.0359 - val_mse: 109.0359
Epoch 6/100
60/60 [==============================] - 0s 981us/step - loss: 1.6963 - mse: 1.6963 - val_loss: 69.0603 - val_mse: 69.0603
Epoch 7/100
60/60 [==============================] - 0s 981us/step - los

60/60 [==============================] - 0s 1ms/step - loss: 0.0058 - mse: 0.0058 - val_loss: 42.1753 - val_mse: 42.1753
Epoch 60/100
60/60 [==============================] - 0s 1ms/step - loss: 0.0038 - mse: 0.0038 - val_loss: 41.4338 - val_mse: 41.4338
Epoch 61/100
60/60 [==============================] - 0s 1ms/step - loss: 0.0020 - mse: 0.0020 - val_loss: 40.5505 - val_mse: 40.5505
Epoch 62/100
60/60 [==============================] - 0s 1ms/step - loss: 0.0062 - mse: 0.0062 - val_loss: 41.3723 - val_mse: 41.3723
Epoch 63/100
60/60 [==============================] - 0s 1ms/step - loss: 0.0034 - mse: 0.0034 - val_loss: 40.4542 - val_mse: 40.4542
Epoch 64/100
60/60 [==============================] - 0s 1ms/step - loss: 0.0048 - mse: 0.0048 - val_loss: 42.0866 - val_mse: 42.0866
Epoch 65/100
60/60 [==============================] - 0s 981us/step - loss: 0.0018 - mse: 0.0018 - val_loss: 41.3814 - val_mse: 41.3814
Epoch 66/100
60/60 [==============================] - 0s 931us/step - los